### ISSUE TITLE
Glitch with C++11 extension [-Wc++11-extensions] 

### ISSUE THREAD

**Issue by CSPRNG** [thibault-martinez/iota.lib.cpp#226] opened 2018-02-17 13:18 UTC
The C++11 extension [-Wc++11-extensions]  reported below do not allow the make process to finish.
using MacOS Sierra version 10.12.6
I have these options in .bash_profile to use clang++ rather than g++ with newer  c++11 and libc++ 

export CC="/usr/local/opt/llvm/bin/clang"
export CXX="/usr/local/opt/llvm/bin/clang++"
export COMPILER="clang++ -std=c++11 -stdlib=libc++"

I have seen other recommended ways to implement similar code avoiding the C++11 extensions, because they cause problems sometimes.
Perhaps you should use code that depends less on latest features or extensions and it is more compatible with the majority of environments.

Any suggestions ? 

……………………..

[ 80%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vauth/spnego_gssapi.c.o
[ 80%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vauth/spnego_sspi.c.o
[ 81%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/openssl.c.o
[ 82%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/gtls.c.o
[ 82%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/vtls.c.o
[ 83%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/nss.c.o
[ 84%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/polarssl.c.o
[ 85%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/polarssl_threadlock.c.o
[ 85%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/axtls.c.o
[ 86%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/cyassl.c.o
[ 87%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/schannel.c.o
[ 87%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/darwinssl.c.o
[ 88%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/gskit.c.o
[ 89%] Building C object opt/curl/lib/CMakeFiles/libcurl.dir/vtls/mbedtls.c.o
[ 90%] Linking C shared library /Users/benutzer/Dev/iota.lib.cpp/deps/lib/libcurl.dylib
[ 90%] Built target libcurl
Scanning dependencies of target cpr
[ 90%] Building CXX object cpr/CMakeFiles/cpr.dir/auth.cpp.o
In file included from /iota.lib.cpp/external/cpr/cpr/auth.cpp:1:
/iota.lib.cpp/external/cpr/include/cpr/auth.h:13:28: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    Authentication(UserType&& username, PassType&& password)
                           ^
/iota.lib.cpp/external/cpr/include/cpr/auth.h:13:49: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    Authentication(UserType&& username, PassType&& password)
                                                ^
/iota.lib.cpp/external/cpr/include/cpr/auth.h:14:43: error: expected member name or ';' after declaration specifiers
            : username_{CPR_FWD(username)}, password_{CPR_FWD(password)},
                                          ^
/iota.lib.cpp/external/cpr/include/cpr/auth.h:14:24: error: expected '('
            : username_{CPR_FWD(username)}, password_{CPR_FWD(password)},
                       ^
/iota.lib.cpp/external/cpr/include/cpr/auth.h:14:42: error: expected ';' after expression
            : username_{CPR_FWD(username)}, password_{CPR_FWD(password)},
                                         ^
                                         ;
/iota.lib.cpp/external/cpr/cpr/auth.cpp:5:51: error: expected function body after function declarator
const char* Authentication::GetAuthString() const noexcept {
                                                  ^
2 warnings and 4 errors generated.
make[5]: *** [cpr/CMakeFiles/cpr.dir/auth.cpp.o] Error 1
make[4]: *** [cpr/CMakeFiles/cpr.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [cpr_dep-prefix/src/cpr_dep-stamp/cpr_dep-build] Error 2
make[1]: *** [CMakeFiles/cpr_dep.dir/all] Error 2
make: *** [all] Error 2

**Comment by Cylix** [comment] 2018-02-17 18:52
Hi,

This compilation error occurs on one of our dependency, for which we are not responsible for the code implementation decision.

Still, the compiler error means that you are not using c++11.
We do not support c++ versions prior to c++11 as c++11 is now the standard c++ version and brings a considerable number of advantages compared to earlier c++ versions.
Thus, you will **not** be able to compile this project and its dependencies without using c++11 extensions.

Would you mind sharing what problems you sometimes get while using the c++11 extensions?

Best

**Comment by CSPRNG** [comment] 2018-02-18 09:42
Hi
I do not mind to use c++11 extensions , in fact tried several suggestions to make them work but it does not work. For example

export COMPILER="/usr/local/opt/llvm/bin/clang++ -std=c++11 -stdlib=libc++"
export CXXFLAGS="-std=c++11 -stldib=libc++" (this is detected but rejected as unknown flags)
Tried in CmakeList.txt:
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
# C++14: set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1y")

According to searches on the web the support for the c++11 extensions depends on the compiler, versions, vendors, which set of extensions, etc.  MacOS sometimes use old libraries because they claim the new ones and open source ones are not safe. In general nothing that is predictable, and the problems are very common.

The code that fails in my case is rather exoteric, using rvalue references && which in the best case is difficult to even comprehend, just read the several pages "simple tutorials" just trying to define lvalue and rvalue, mix that with templates and iffy supported extensions and no wonder it is going to break. 

Code for crypto security should be less convoluted, who is going to review and vouch for this type of code ? .

If you tested your system in a MacOS environment let me know what is the correct way to configure everything to make it run, swithces, flags, etc.

**Comment by Cylix** [comment] 2018-02-18 18:52
Our CMake already configures the compiler to use C++11, so you should not need to specify std=c++11 or stdlib=libc++.

If you want to force cmake to use either gcc/g++ or clang/clang++, you need to use the CC and CXX environment variable.

For example:
```
CC=/usr/local/opt/llvm/bin/clang
CXX=/usr/local/opt/llvm/bin/clang++
cmake .
make
```

Again, the code you saw is not ours, but the dependency we use to make our HTTP requests to the IOTA node. We do not need to review it as the library is already widely used.
Our code is currently much easier to apprehend as we do not mix yet that kind of concept. However, we may use them later on as these are core modern C++ concept enabling powerful code re-use (template) or code optimization (rvalue reference).

Let me know if the CC/CXX solves your issue, otherwise I'll try to find another solution :)

Best

**Comment by CSPRNG** [comment] 2018-02-19 10:12
I already use that in the .bash_profile,here is the terminal output

$ cmake ..
-- The C compiler identification is Clang 4.0.1
-- The CXX compiler identification is Clang 4.0.1
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done

I suspect the problem has something to do with the Variadic_macro CPR_FWD(...) and the issue of trailing commas. Different compilers handle this problem differently, and it is a design bug in C++ , but who knows, this code is overtly "modern".

#include "cpr/auth.h"
#define CPR_FWD(...) ::std::forward<decltype(__VA_ARGS__)>(__VA_ARGS__)

Modern language features do not equate to safe features, and there is nothing modern or safe in buggy Variadic_macros, these are relics from C preprocessor times..

**Comment by Cylix** [comment] 2018-02-19 22:02
Seems you are using Clang 4.0.1: we do use this version of CLang in one of our Travis build and it works fine. For example, here is a recent build from the master branch using CLang 4.0.1. https://travis-ci.org/thibault-martinez/iota.lib.cpp/jobs/343497785 

Thus, as of now, we can't reproduce the bug either locally or on a testing server.
To help us better identify the root cause of the issue, would you mind do the following:
* Give us the iota.lib.cpp version you are using. More specifically, if you downloaded the library using git, can you give us the most recent commit you are trying to build by doing a git log and giving us the git hash ref of the latest commit
* Give us the exact version of clang you are using (running a clang++ --version)
* Give us the operating system you are compiling on (uname -a)
* Modify this line of the CMakelists.txt: https://github.com/thibault-martinez/iota.lib.cpp/blob/master/CMakeLists.txt#L38 by setting the option to ON rather than OFF
* Deleting the deps and build directory, rerun cmake and make and copy us the entire output (including the commands you run). If the output is too long, you can create a pastebin on pastebin.com and reply with a link to it. The output should contain lot more detailed information thanks to the verbose flag set to ON from the previous step. If not, you may need to double check you effectively enabled the verbose flag and rerun cmake.

Also, does this issue occurs when you are compiling with another compiler (like gcc/g++ or another version of clang)?

As soon as I get all these information, I will be able to diagnose this issue.

Finally, I want to clarify that we are not responsible for the implementation choice of our dependencies.
If `cpr` decides to use these features from C++11, they do so by themselves.
Moreover, I strongly believe that their implementation choices are safe, strong and modern. This library got over 1.5K stars on Github, which is very high for a C++ library, started to be developed in 2015, has over 30 contributors and we never got any issues with it on different platforms/architecture (ubuntu, macos, debian, windows, 32/64 bits) and several compiler (clang/gcc on different versions).

The only thing I personally dislike concerning CPR is their buildchain configuration which makes it harder for us to configure our buildchain on all the platforms we support, but it has no impact on unix/mac platforms.

In the case where there is something wrong on their side, we will only be able to notify them or submit a PR to their repository with no insurance it is going to be merged. I also prefer to first diagnose possible configuration issue on your or our side. 

Best

**Comment by Cylix** [comment] 2018-02-19 22:03
Also, are you building in Debug or Release configuration?
You can specify that to cmake by using -DCMAKE_BUILD_TYPE=Release (or Debug).

Best

**Comment by thibault-martinez** [comment] 2018-03-25 14:52
Without any news from OP by the end of next week, I'll close this issue.

**Comment by Cylix** [comment] 2018-04-03 05:28
In the absence of answer, I'm closing this issue.
However, feel free to re-open it in the future if you wish to share more details about it.
Best

**Closed by Cylix** 2018-04-03 05:28 UTC
