### ISSUE TITLE
investigate empty response

### ISSUE THREAD

**Issue by Cylix** [thibault-martinez/iota.lib.cpp#139] opened 2017-09-29 22:00 UTC
responses/broadcast_transactions
responses/interrupt_attaching_to_tangle
responses/store_transactions

These responses are basically empty: no fields, no serializations, no getters.
Is that normal? What are the related APIs supposed to return?
Seems these class can be removed.

**Comment by thibault-martinez** [comment] 2017-09-29 23:08
I can confirm that these APIs doesn't respond, classes can be removed.

Seems like it' done in #138 , closing this issue.

**Comment by Cylix** [comment] 2017-09-29 23:09
mmh, no #138 removes .cpp, not .hpp: should we remove hpp?

**Comment by thibault-martinez** [comment] 2017-09-29 23:11
Ohh my bad.

I think we should, I'll make Core APIs return void after having merged #138.

**Comment by thibault-martinez** [comment] 2017-09-29 23:14
Not void.

Returning a generic response due to the service templates.

**Closed** 2017-09-30 08:54 UTC
Labels: question
